ctl_start now a helper that runs as a user

diff --git a/jobs/gitlabhq/templates/bin/ctl_start.sh.erb b/jobs/gitlabhq/templates/bin/ctl_start.sh.erb
--- a/jobs/gitlabhq/templates/bin/ctl_start.sh.erb
+++ b/jobs/gitlabhq/templates/bin/ctl_start.sh.erb
@@ -23,37 +23,41 @@
 # * $WEBAPP_DIR
 # * $PIDFILE
 # * $PORT
-appstack='<%= properties.webapp && properties.webapp.appstack %>'
+function ctl_start() {
+  user=${1:-vcap}
+  appstack='<%= properties.webapp && properties.webapp.appstack %>'
 
-echo "Launching $JOB_NAME within $WEBAPP_DIR with ${appstack}"
-wait_for_database
+  echo "Launching $JOB_NAME within $WEBAPP_DIR with ${appstack}"
+  wait_for_database
 
-if [[ "${appstack}" = "puma" ]]
-then
-  <% puma_threads = properties.webapp.puma && properties.webapp.puma.threads %>
-  MIN_THREADS=<%= (puma_threads && puma_threads.min) || 0 %>
-  MAX_THREADS=<%= (puma_threads && puma_threads.max) || 16 %>
-  exec bundle exec puma --pidfile $PIDFILE -p $PORT -t $MIN_THREADS:$MAX_THREADS \
-       >>$LOG_DIR/webapp.stdout.log \
-       2>>$LOG_DIR/webapp.stderr.log || exit 1
+  if [[ "${appstack}" = "puma" ]]
+  then
+    <% puma_threads = properties.webapp.puma && properties.webapp.puma.threads %>
+    MIN_THREADS=<%= (puma_threads && puma_threads.min) || 0 %>
+    MAX_THREADS=<%= (puma_threads && puma_threads.max) || 16 %>
+    chpst -u ${user}:${user} bundle exec puma --pidfile $PIDFILE -p $PORT -t $MIN_THREADS:$MAX_THREADS \
+         >>$LOG_DIR/webapp.stdout.log \
+         2>>$LOG_DIR/webapp.stderr.log || exit 1
 
-elif [[ "${appstack}" = "rackup" ]]
-then
-  exec bundle exec rackup -D -P $PIDFILE -p $PORT \
-       >>$LOG_DIR/webapp.stdout.log \
-       2>>$LOG_DIR/webapp.stderr.log || exit 1
+  elif [[ "${appstack}" = "rackup" ]]
+  then
+    chpst -u ${user}:${user} bundle exec rackup -D -P $PIDFILE -p $PORT \
+         >>$LOG_DIR/webapp.stdout.log \
+         2>>$LOG_DIR/webapp.stderr.log || exit 1
 
-elif [[ "${appstack}" = "phpfpm" || "${appstack}" = "php-fpm" ]]
-then
-  /var/vcap/packages/php5/sbin/php-fpm \
-    -c $JOB_DIR/etc/php.ini \
-    --fpm-config $JOB_DIR/etc/php-fpm.conf \
-    --pid $PIDFILE
+  elif [[ "${appstack}" = "phpfpm" || "${appstack}" = "php-fpm" ]]
+  then
+    chpst -u ${user}:${user} /var/vcap/packages/php5/sbin/php-fpm \
+      -c $JOB_DIR/etc/php.ini \
+      --fpm-config $JOB_DIR/etc/php-fpm.conf \
+      --pid $PIDFILE
 
-# else invalid appstack requested
-else
-  echo "ERROR: properties.webapp.appstack = ${appstack}. Valid values: puma, rackup"
-  exit 1
-fi
+  # else invalid appstack requested
+  else
+    echo "ERROR: properties.webapp.appstack = ${appstack}. Valid values: puma, rackup"
+    exit 1
+  fi
 
-chown vcap:vcap $PIDFILE
+  chown vcap:vcap $PIDFILE
+}
+
